# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10aa4e5bc015d555fb0741a1f0b0b245282bc8c818c2807a9eb4ff4010234204bbdecbfca498fb0d11f94c4cede1294fda56729a18b47d4bb8f1ea9c81a43818

test:
  secret_key_base: aa8b2e49cca2b92c020331d9128c908990fd97aa79e74476e0b2df8e231c5045513514b54cf2288c16f7c9faaa2ffe56b965451e8dbcb4e354f83b5c4bac2277

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
